CREATE TABLE Users (
	UserId INT PRIMARY KEY IDENTITY(1, 1), 
	NickName NVARCHAR(50) UNIQUE NOT NULL, 
	Email NVARCHAR(100) UNIQUE NOT NULL, 
	UserName NVARCHAR(50) UNIQUE NOT NULL, 
	PasswordHash NVARCHAR(60) NOT NULL, 
	UserRole INT NOT NULL, 
	RegisterDate DATETIME2(7) DEFAULT SYSDATETIME(), 
	RefreshToken NVARCHAR(255) NOT NULL, 
	RefreshTokenExpiry DATETIME2(7)
);

CREATE TABLE Clubs (
	ClubId INT PRIMARY KEY IDENTITY(1, 1), 
	ClubName NVARCHAR(100) UNIQUE NOT NULL, 
	Sport INT NOT NULL, 
	Phone NVARCHAR(20) UNIQUE NOT NULL, 
	Email NVARCHAR(100) UNIQUE NOT NULL, 
	ClubDescription NVARCHAR(255) UNIQUE NOT NULL, 
	EstablishedTime DATETIME2(7) DEFAULT SYSDATETIME() 
);